console.log("Primeira linha \nSegunda linha")
console.log("O Meu nome é 'Renato'")
console.log('O nome dela é "Roberta"')
console.log(`A multiplicação de 5 por 3 é ${5* 3}`)
console.log("O "+ "meu " + "nome " + "é " + "Renato.")